name: mabl

on: 
  workflow_call:
#on:
#  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:

  build:
    if: ${{ ( github.event.pull_request.merged == true ) && ( !contains( github.event.pull_request.title, 'skip mabl' )) }} 
    runs-on: ubuntu-latest
    steps:
      - name: test3
        run: echo "test3"

      - name: test4
        run: echo "test4"
