name: mabl

on: push  
#on:
#  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:

  build:
    if: ${{ ( github.event.pull_request.merged == true ) && ( !contains( github.event.pull_request.title, 'skip mabl' )) }} 
    runs-on: ubuntu-latest
    steps:
      - run: echo "test3"
      if: ${{ github.actor != 'dependabot[bot]' }} 
      - run: echo "test4"
